# This is a config for E2B sandbox template.
# You can use template ID (885hgtudur7t1s03pc21) or template name (lovable-clone-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("lovable-clone-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-clone-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-clone-test-2')

team_id = "6c9a5ed0-181f-48e4-915a-45f45ccd8fd5"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-clone-test-2"
template_id = "885hgtudur7t1s03pc21"
